tools:
  alpha_agent:
    level: 3
    type: llm_call_agent
    available_tools:
      - material_to_document_agent
      - data_collection_agent
      - data_analysis_agent
      - coder_agent
      - create_figures_agent
      - human_in_loop
      - judge_agent
      - file_read
      - file_write
      - file_move
      - dir_list
      - dir_create
      - reference_list
      - reference_add
      - reference_delete
      - final_output
    max_turns: 100
    model_type: claude-3-7-sonnet-20250219
    prompts:
      agent_responsibility: |
        你的职责是一个通用的 AI 助手，可以撰写论文，和用户对话，调研，科学研究等等工作。
      agent_workflow: |
        **你的流程:**
        1. 详细分析用户的意图，并根据意图编排使用你的工具完成任务。
        例如，如果用户想要进行学术论文写作，则你应该依次调用：
        1. 使用data_collection_agent工具收集相关文献
        2. 使用data_analysis_agent工具获取实验想法和计划
        3. 使用coder_agent完成实验（如果是代码实验）
        4. 使用create_figures_agent将实验数据转换为图表，该 agent 也可以生成框架图，写实图像等各种类型的图像。
        5. 使用material_to_paper_agent工具将实验数据和图表转换为论文
        6. 使用judge_agent工具判断论文是否符合要求
        7. 使用final_output工具输出自己已经完成任务的情况
        如果用户不是传统的学术论文写作需求，你应该自己编排选择合适的工具完成,基于你的经验和任务难度，有时候并不是所有任务都要用到上述所有智能体功能。你作为直接和用户接触的 agent，还可能遇到基于历史任务和文件空间的单纯的聊天，询问等需求，使用human_in_loop工具和用户进行对话交互。
        这种时候直接调用 final_output工具完成即可。如果用户在需求确认和探讨阶段，你也可以调用 human_in_loop工具和用户进行对话交互。
        不要越界，对应任务交给对应的智能体，无需为其建立文件夹等操作。
    name: "alpha_agent"
    description: "根据用户的写作意图，编排使用你的工具完成任务"
    parameters:
      type: "object"
      properties:
        task_id:
          type: "string"
          description: "任务的唯一ID。"
        task_input:
          type: "string"
          description: "用户写作需求的初始指令"
        max_turns:
          type: "integer"
          default: 1000
          description: "文献收集过程的最大轮次，防止无限循环。可选。"
      required: ["task_id", "task_input"]
  

  # deep_research_agent:
  #   level: 3
  #   type: llm_call_agent
  #   available_tools:
  #     # - material_to_document_agent
  #     - data_collection_agent
  #     # - data_analysis_agent
  #     - judge_agent
  #     - final_output
  #     - file_read
  #     - file_write
  #     - file_move
  #     - dir_list
  #     - dir_create
  #     - answer_from_papers
  #   max_turns: 100
  #   model_type: claude-3-7-sonnet-20250219
  #   prompts:
  #     agent_responsibility: |
  #       你的职责是撰写深度研究报告！。
  #     agent_workflow: |
  #       **你的流程:**
  #       根据主题生成深度调研的报告，对子 agent 输入需求时，一定要强调收集资料的翔实，基于资料观点见解的新颖和洞察深度！
  #       1. 使用data_collection_agent收集相关资料，要求详实,但是不要要求过多例如十几篇论文完全没必要！最好直接在参数处输入哪几个方面的资料。使用 file_read和answer_from_papers阅读材料。
  #       2. 先得出新颖的洞察，记录洞察在一个单独文件中，要求其洞察必须深刻，新颖，有见地！
  #       3. 同时构思大纲和深度报告的撰写逻辑。
  #       3. 使用file_write append模式将资料转化为完整的报告，要求基于大纲的思路将前面**所有**分析，资料，数据整合(不是简单复制，而是基于大纲融合）到一个完整的 report_final.md的报告中去，篇幅不能低于 10000 字，参考文献也要整合到主 md 报告中。（你不可能一次性输出，使用 append 模式分步输入到最终报告中）
  #       4. 使用final_output工具输出自己已经完成任务的情况
  #       最重要的一点！！！：最后的报告必须由material_to_paper_agent基于前面的资料完成，不要接收任何其他 agent 产生的报告作为输出！
  #   name: "deep_research_agent"
  #   description: "根据用户的写作意图，编排使用你的工具完成任务"
  #   parameters:
  #     type: "object"
  #     properties:
  #       task_id:
  #         type: "string"
  #         description: "任务的唯一ID。"
  #       task_input:
  #         type: "string"
  #         description: "用户写作需求的初始指令"
  #       max_turns:
  #         type: "integer"
  #         default: 1000
  #         description: "文献收集过程的最大轮次，防止无限循环。可选。"
  #     required: ["task_id", "task_input"]

 