temperature: 0
max_tokens: 0
max_context_window: 200000
base_url: https://openrouter.ai/api/v1
# api_key: your-api-key-here
api_key: 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
models:
  - openai/openai/gpt-5
