temperature: 0
max_tokens: 0
max_context_window: 200000
base_url: your provider'url for example: https://XXXX.top/v1 / 你供应商提供的 url
api_key: yourkey
models:
# 如果供应商提供的是 openai 格式前缀填写openai,如果是anthropic格式前缀填写anthropic
# 注意前缀名称和站点模型无关，前缀后再填写运营商提供的模型名称，例如 openrouter 提供
# 了openai格式的gpt-4o,模型名为 openai/gpt-4o，则应该填写 openai/openai/gpt-4o
# 如果模型厂商提供的是 gpt-4o，则直接填写 openai/gpt-4o即可
- openai/claude-haiku-4-5-20251001
figure_models:
#同理，除了openrouter不用填写以外，其他第三方需要填写请求格式前缀，方便路由对应格式
- openai/dall-e-3 
compressor_models:
- openai/claude-haiku-4-5-20251001
read_figure_models:
- openai/gpt-4o